# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import django.contrib.auth.models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAmenities',
            fields=[
                ('extra_amenity_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('extra_amenity', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('advert_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('status', models.CharField(default=b'1', max_length=150, null=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('advert_name', models.CharField(max_length=50, null=True, blank=True)),
                ('website', models.CharField(max_length=50, null=True, blank=True)),
                ('latitude', models.CharField(max_length=50, null=True, blank=True)),
                ('longitude', models.CharField(max_length=50, null=True, blank=True)),
                ('short_description', models.CharField(max_length=5000, null=True, blank=True)),
                ('product_description', models.CharField(max_length=5000, null=True, blank=True)),
                ('discount_description', models.CharField(max_length=5000, null=True, blank=True)),
                ('display_image', models.FileField(max_length=500, null=True, upload_to=b'images/user_images/', blank=True)),
                ('address_line_1', models.CharField(max_length=50, null=True, blank=True)),
                ('address_line_2', models.CharField(max_length=50, null=True, blank=True)),
                ('area', models.CharField(max_length=50, null=True, blank=True)),
                ('landmark', models.CharField(max_length=50, null=True, blank=True)),
                ('email_primary', models.CharField(max_length=50, null=True, blank=True)),
                ('email_secondary', models.CharField(max_length=50, null=True, blank=True)),
                ('property_market_rate', models.CharField(max_length=50, null=True, blank=True)),
                ('possesion_status', models.CharField(max_length=50, null=True, blank=True)),
                ('other_projects', models.CharField(max_length=5000, null=True, blank=True)),
                ('date_of_delivery', models.CharField(max_length=50, null=True, blank=True)),
                ('any_other_details', models.CharField(max_length=5000, null=True, blank=True)),
                ('speciality', models.CharField(max_length=5000, null=True, blank=True)),
                ('happy_hour_offer', models.CharField(max_length=5000, null=True, blank=True)),
                ('course_duration', models.CharField(max_length=5000, null=True, blank=True)),
                ('affilated_to', models.CharField(max_length=5000, null=True, blank=True)),
                ('facility', models.CharField(max_length=5000, null=True, blank=True)),
                ('image_video_space_used', models.CharField(max_length=200, null=True, blank=True)),
                ('distance_frm_railway_station', models.CharField(max_length=50, null=True, blank=True)),
                ('distance_frm_railway_airport', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_views', models.CharField(max_length=10, null=True, blank=True)),
                ('keywords', models.CharField(max_length=1000, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advert_Category_Map',
            fields=[
                ('adv_cat_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('category_level', models.CharField(max_length=30, null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advert_Video',
            fields=[
                ('advert_video_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('advert_video_name', models.FileField(max_length=500, null=True, upload_to=b'images/user_images/', blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(related_name='advert_videos', blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertFavourite',
            fields=[
                ('id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('advert_image_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('advert_image', models.FileField(max_length=500, null=True, upload_to=b'images/user_images/', blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertLike',
            fields=[
                ('id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertRateCard',
            fields=[
                ('advert_rate_card_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('advert_service_name', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30, null=True, blank=True)),
                ('cost', models.CharField(max_length=30, null=True, blank=True)),
                ('advert_rate_card_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('advert_rate_card_created_date', models.DateTimeField(null=True, blank=True)),
                ('advert_rate_card_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('advert_rate_card_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('advert_rate_card_updated_date', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertSubscriptionMap',
            fields=[
                ('id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenity_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('amenity', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('duration', models.CharField(max_length=30)),
                ('transaction_code', models.CharField(max_length=30, null=True, blank=True)),
                ('start_date', models.CharField(max_length=30, null=True, blank=True)),
                ('end_date', models.CharField(max_length=30, null=True, blank=True)),
                ('business_created_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('business_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('business_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('business_updated_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('is_active', models.CharField(max_length=2, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('category_name', models.CharField(max_length=30)),
                ('category_color', models.CharField(max_length=30, null=True, blank=True)),
                ('category_image', models.ImageField(default=None, null=True, upload_to=b'images/user_images/', blank=True)),
                ('category_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('category_created_date', models.DateTimeField(null=True, blank=True)),
                ('category_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_date', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCityMap',
            fields=[
                ('map_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('sequence', models.CharField(max_length=500, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('category_id', models.ForeignKey(blank=True, to='digispaceapp.Category', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel1',
            fields=[
                ('category_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('category_name', models.CharField(max_length=30)),
                ('category_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('category_created_date', models.DateTimeField(null=True, blank=True)),
                ('category_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_date', models.DateTimeField(null=True, blank=True)),
                ('parent_category_id', models.ForeignKey(blank=True, to='digispaceapp.Category', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel2',
            fields=[
                ('category_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('category_name', models.CharField(max_length=30)),
                ('category_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('category_created_date', models.DateTimeField(null=True, blank=True)),
                ('category_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_date', models.DateTimeField(null=True, blank=True)),
                ('parent_category_id', models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel1', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel3',
            fields=[
                ('category_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('category_name', models.CharField(max_length=30)),
                ('category_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('category_created_date', models.DateTimeField(null=True, blank=True)),
                ('category_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_date', models.DateTimeField(null=True, blank=True)),
                ('parent_category_id', models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel2', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel4',
            fields=[
                ('category_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('category_name', models.CharField(max_length=30)),
                ('category_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('category_created_date', models.DateTimeField(null=True, blank=True)),
                ('category_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_date', models.DateTimeField(null=True, blank=True)),
                ('parent_category_id', models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel3', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel5',
            fields=[
                ('category_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('category_name', models.CharField(max_length=30)),
                ('category_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('category_created_date', models.DateTimeField(null=True, blank=True)),
                ('category_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('category_updated_date', models.DateTimeField(null=True, blank=True)),
                ('parent_category_id', models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel4', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('city_name', models.CharField(max_length=100, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('city_status', models.CharField(default=b'1', max_length=10, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
            ],
        ),
        migrations.CreateModel(
            name='City_Place',
            fields=[
                ('city_place_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('currency', models.CharField(max_length=500, null=True, blank=True)),
                ('about_city', models.CharField(max_length=1000, null=True, blank=True)),
                ('city_image', models.FileField(max_length=500, null=True, upload_to=b'images/user_images/', blank=True)),
                ('climate', models.CharField(max_length=500, null=True, blank=True)),
                ('language', models.CharField(max_length=100, null=True, blank=True)),
                ('population', models.CharField(max_length=100, null=True, blank=True)),
                ('time_zone', models.CharField(max_length=100, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('city_status', models.CharField(default=b'1', max_length=10, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('city_id', models.ForeignKey(to='digispaceapp.City', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer_Feedback',
            fields=[
                ('feedback_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('consumer_feedback', models.CharField(max_length=1000, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerProfile',
            fields=[
                ('user_ptr', models.OneToOneField(parent_link=True, auto_created=True, to=settings.AUTH_USER_MODEL)),
                ('consumer_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('consumer_full_name', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('consumer_contact_no', models.CharField(default=None, max_length=200, null=True, blank=True)),
                ('consumer_email_id', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('consumer_status', models.CharField(default=b'1', max_length=100, null=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('consumer_created_date', models.DateTimeField(null=True, blank=True)),
                ('consumer_created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('consumer_updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('consumer_updated_date', models.DateTimeField(null=True, blank=True)),
                ('sign_up_source', models.CharField(max_length=20, null=True, blank=True)),
                ('consumer_profile_pic', models.ImageField(default=None, upload_to=b'images/user_images/', max_length=500, verbose_name=b'Image')),
                ('device_token', models.CharField(max_length=20, null=True, blank=True)),
                ('online', models.CharField(default=b'1', max_length=100, null=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('last_time_login', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('latitude', models.FloatField(default=None, max_length=20, null=True, blank=True)),
                ('longitude', models.FloatField(default=None, max_length=20, null=True, blank=True)),
                ('consumer_area', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('user_verified', models.CharField(default=b'false', max_length=100, null=True, choices=[(b'true', b'true'), (b'false', b'false')])),
                ('notification_status', models.CharField(default=b'true', max_length=100, null=True, choices=[(b'true', b'true'), (b'false', b'false')])),
                ('push_review_status', models.CharField(default=b'true', max_length=100, null=True, choices=[(b'true', b'true'), (b'false', b'false')])),
                ('push_post_status', models.CharField(default=b'true', max_length=100, null=True, choices=[(b'true', b'true'), (b'false', b'false')])),
                ('push_social_status', models.CharField(default=b'true', max_length=100, null=True, choices=[(b'true', b'true'), (b'false', b'false')])),
                ('email_review_status', models.CharField(default=b'true', max_length=100, null=True, choices=[(b'true', b'true'), (b'false', b'false')])),
                ('newsletter_status', models.CharField(default=b'true', max_length=100, null=True, choices=[(b'true', b'true'), (b'false', b'false')])),
                ('email_social_status', models.CharField(default=b'true', max_length=100, null=True, choices=[(b'true', b'true'), (b'false', b'false')])),
                ('no_of_login', models.CharField(default=None, max_length=100, null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                (b'objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('country_name', models.CharField(max_length=500, null=True, blank=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('country_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('coupon_code', models.CharField(max_length=20, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
                ('user_id', models.ForeignKey(blank=True, to='digispaceapp.ConsumerProfile', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(serialize=False, primary_key=True)),
                ('currency', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(default=b'1', max_length=150, null=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('created_by', models.CharField(max_length=150, null=True, blank=True)),
                ('created_date', models.DateTimeField(null=True, blank=True)),
                ('updated_by', models.CharField(max_length=150, null=True, blank=True)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('country_id', models.ForeignKey(to='digispaceapp.Country', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NearByAttraction',
            fields=[
                ('attraction_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('attraction', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NearestHospital',
            fields=[
                ('hospital_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('hospital_name', models.CharField(max_length=50, null=True, blank=True)),
                ('distance_frm_property', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NearestSchool',
            fields=[
                ('school_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('school_name', models.CharField(max_length=50, null=True, blank=True)),
                ('distance_frm_property', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NearestShopping',
            fields=[
                ('shopping_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('shop_name', models.CharField(max_length=50, null=True, blank=True)),
                ('distance_frm_property', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('payment_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('payment_code', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=50, null=True, blank=True)),
                ('branch_name', models.CharField(max_length=50, null=True, blank=True)),
                ('cheque_number', models.CharField(max_length=50, null=True, blank=True)),
                ('paid_amount', models.CharField(max_length=30, null=True, blank=True)),
                ('payable_amount', models.CharField(max_length=30, null=True, blank=True)),
                ('total_amount', models.CharField(max_length=30, null=True, blank=True)),
                ('payment_created_date', models.DateTimeField(null=True, blank=True)),
                ('payment_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('payment_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('payment_updated_date', models.DateTimeField(null=True, blank=True)),
                ('note', models.CharField(max_length=30, null=True, blank=True)),
                ('business_id', models.ForeignKey(blank=True, to='digispaceapp.Business', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCategory',
            fields=[
                ('phone_category_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('phone_category_name', models.CharField(max_length=15)),
                ('phone_category_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('phone_category_created_date', models.DateTimeField(null=True, blank=True)),
                ('phone_category_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('phone_category_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('phone_category_updated_date', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNo',
            fields=[
                ('phone_no_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('phone_no', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
                ('phone_category_id', models.ForeignKey(blank=True, to='digispaceapp.PhoneCategory', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('pincode_id', models.AutoField(serialize=False, primary_key=True)),
                ('pincode', models.CharField(default=None, max_length=250, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('created_by', models.CharField(default=None, max_length=30, null=True, blank=True)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('updated_by', models.CharField(default=None, max_length=30, null=True, blank=True)),
                ('pincode_status', models.CharField(default=b'1', max_length=10, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('city_id', models.ForeignKey(blank=True, to='digispaceapp.City', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_id', models.AutoField(serialize=False, primary_key=True)),
                ('place_name', models.CharField(default=None, max_length=250, null=True, blank=True)),
                ('place_image', models.FileField(max_length=500, null=True, upload_to=b'images/user_images/', blank=True)),
                ('place_type', models.CharField(default=None, max_length=30, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('created_by', models.CharField(default=None, max_length=30, null=True, blank=True)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('updated_by', models.CharField(default=None, max_length=30, null=True, blank=True)),
                ('city_place_id', models.ForeignKey(blank=True, to='digispaceapp.City_Place', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumService',
            fields=[
                ('premium_service_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('premium_service_name', models.CharField(max_length=30)),
                ('no_of_days', models.CharField(max_length=30)),
                ('start_date', models.CharField(max_length=30, null=True, blank=True)),
                ('end_date', models.CharField(max_length=30, null=True, blank=True)),
                ('premium_service_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('premium_service_created_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('premium_service_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('premium_service_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('premium_service_updated_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('business_id', models.ForeignKey(blank=True, to='digispaceapp.Business', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('privilege_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('privilage', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('created_by', models.CharField(default=None, max_length=30, null=True, blank=True)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('updated_by', models.CharField(default=None, max_length=30, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('product_name', models.CharField(max_length=50, null=True, blank=True)),
                ('product_price', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellTicket',
            fields=[
                ('sellticket_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('event_name', models.CharField(max_length=50, null=True, blank=True)),
                ('event_venue', models.CharField(max_length=50, null=True, blank=True)),
                ('start_date', models.DateTimeField(null=True, blank=True)),
                ('start_time', models.CharField(max_length=50, null=True, blank=True)),
                ('select_activation_date', models.CharField(max_length=50, null=True, blank=True)),
                ('other_comments', models.CharField(max_length=5000, null=True, blank=True)),
                ('ticket_class', models.CharField(max_length=50, null=True, blank=True)),
                ('no_of_tickets', models.CharField(max_length=50, null=True, blank=True)),
                ('original_price', models.CharField(max_length=50, null=True, blank=True)),
                ('asking_price', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_number', models.CharField(max_length=20, null=True, blank=True)),
                ('image_one', models.ImageField(default=None, upload_to=b'images/user_images/', max_length=500, verbose_name=b'Image')),
                ('image_two', models.ImageField(default=None, upload_to=b'images/user_images/', max_length=500, verbose_name=b'Image')),
                ('image_three', models.ImageField(default=None, upload_to=b'images/user_images/', max_length=500, verbose_name=b'Image')),
                ('image_four', models.ImageField(default=None, upload_to=b'images/user_images/', max_length=500, verbose_name=b'Image')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('user_id', models.ForeignKey(blank=True, to='digispaceapp.ConsumerProfile', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRateCard',
            fields=[
                ('service_rate_card_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('service_name', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30, null=True, blank=True)),
                ('cost', models.CharField(max_length=30, null=True, blank=True)),
                ('service_rate_card_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('service_rate_card_created_date', models.DateTimeField(null=True, blank=True)),
                ('service_rate_card_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('service_rate_card_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('service_rate_card_updated_date', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('state_name', models.CharField(max_length=500, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('state_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('country_id', models.ForeignKey(to='digispaceapp.Country', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user_ptr', models.OneToOneField(parent_link=True, auto_created=True, to=settings.AUTH_USER_MODEL)),
                ('supplier_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('business_name', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('phone_no', models.CharField(default=None, max_length=200, null=True, blank=True)),
                ('secondary_phone_no', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('supplier_email', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('secondary_email', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('logo', models.ImageField(default=None, null=True, upload_to=b'images/user_images/', blank=True)),
                ('address1', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('address2', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('business_details', models.CharField(default=None, max_length=10000, null=True, blank=True)),
                ('contact_person', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('contact_no', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('contact_email', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('supplier_status', models.CharField(default=b'1', max_length=100, null=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('supplier_created_date', models.DateTimeField(default=django.utils.timezone.now, null=True, blank=True)),
                ('supplier_created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('supplier_updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('supplier_updated_date', models.DateTimeField(null=True, blank=True)),
                ('city', models.ForeignKey(blank=True, to='digispaceapp.City', null=True)),
                ('pincode', models.ForeignKey(blank=True, to='digispaceapp.Pincode', null=True)),
                ('state', models.ForeignKey(blank=True, to='digispaceapp.State', null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                (b'objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.AutoField(serialize=False, primary_key=True)),
                ('tax_type', models.CharField(default=None, max_length=50, null=True, blank=True)),
                ('tax_rate', models.IntegerField(max_length=5, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(parent_link=True, auto_created=True, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('user_name', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('user_contact_no', models.CharField(default=None, max_length=200, null=True, blank=True)),
                ('usre_email_id', models.CharField(default=None, max_length=100, null=True, blank=True)),
                ('user_status', models.CharField(default=b'1', max_length=100, null=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('user_created_date', models.DateTimeField(null=True, blank=True)),
                ('user_created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('user_updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('user_updated_date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                (b'objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('role_name', models.CharField(max_length=25)),
                ('role_status', models.CharField(default=b'1', max_length=15, null=True, blank=True, choices=[(b'1', b'1'), (b'0', b'0')])),
                ('role_created_date', models.DateTimeField(null=True, blank=True)),
                ('role_created_by', models.CharField(max_length=30, null=True, blank=True)),
                ('role_updated_by', models.CharField(max_length=30, null=True, blank=True)),
                ('role_updated_date', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('working_hr_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('day', models.CharField(max_length=50, null=True, blank=True)),
                ('start_time', models.CharField(max_length=50, null=True, blank=True)),
                ('end_time', models.CharField(max_length=50, null=True, blank=True)),
                ('creation_date', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updation_date', models.DateTimeField(null=True, blank=True)),
                ('advert_id', models.ForeignKey(blank=True, to='digispaceapp.Advert', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.ForeignKey(blank=True, to='digispaceapp.UserRole', null=True),
        ),
        migrations.AddField(
            model_name='privileges',
            name='role_id',
            field=models.ForeignKey(related_name='userroleid', blank=True, to='digispaceapp.UserRole', null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='tax_type',
            field=models.ForeignKey(blank=True, to='digispaceapp.Tax', null=True),
        ),
        migrations.AddField(
            model_name='consumer_feedback',
            name='consumer_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.ConsumerProfile', null=True),
        ),
        migrations.AddField(
            model_name='city_place',
            name='country_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.Country', null=True),
        ),
        migrations.AddField(
            model_name='city_place',
            name='state_id',
            field=models.ForeignKey(to='digispaceapp.State', blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(to='digispaceapp.State', blank=True),
        ),
        migrations.AddField(
            model_name='categorycitymap',
            name='city_place_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.City_Place', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, to='digispaceapp.Category', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='service_rate_card_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.ServiceRateCard', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='supplier',
            field=models.ForeignKey(blank=True, to='digispaceapp.Supplier', null=True),
        ),
        migrations.AddField(
            model_name='advertsubscriptionmap',
            name='business_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.Business', null=True),
        ),
        migrations.AddField(
            model_name='advertlike',
            name='user_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.ConsumerProfile', null=True),
        ),
        migrations.AddField(
            model_name='advertfavourite',
            name='user_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.ConsumerProfile', null=True),
        ),
        migrations.AddField(
            model_name='advert_category_map',
            name='category_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.Category', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='category_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.Category', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='category_level_1',
            field=models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel1', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='category_level_2',
            field=models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel2', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='category_level_3',
            field=models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel3', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='category_level_4',
            field=models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel4', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='category_level_5',
            field=models.ForeignKey(blank=True, to='digispaceapp.CategoryLevel5', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='city_place_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.City_Place', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='currency_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.Currency', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='pincode_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.Pincode', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='state_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.State', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='supplier_id',
            field=models.ForeignKey(blank=True, to='digispaceapp.Supplier', null=True),
        ),
        migrations.AddField(
            model_name='additionalamenities',
            name='advert_id',
            field=models.ForeignKey(related_name='add_ame', blank=True, to='digispaceapp.Advert', null=True),
        ),
    ]
